# Generated by Django 4.2.9 on 2024-06-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=20)),
                ('available_quantity', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
