# Generated by Django 4.2.9 on 2024-06-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
    ]
