# Generated by Django 4.2.9 on 2024-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_item_available_quantity_stock_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_Name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Supplier_Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
