# Generated by Django 4.2.9 on 2024-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_item_item_name_alter_supplier_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Purchase_Date',
            new_name='Invoice_Date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='Price_per_peice',
        ),
        migrations.AddField(
            model_name='product',
            name='CGST',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Invoice_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='SGST',
            field=models.IntegerField(default=0),
        ),
    ]
