# Generated by Django 4.2.9 on 2024-06-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Punch_Card_NO', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=25)),
                ('Designation', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('DOL', models.DateField()),
                ('Parents_Name', models.CharField(max_length=25)),
                ('Martial_Status', models.CharField(max_length=25)),
                ('Permanent_Address', models.TextField()),
                ('Present_Address', models.TextField()),
                ('Blood_Group', models.CharField(max_length=10)),
                ('UAN_Number', models.IntegerField(null=True, unique=True)),
                ('PF_PW', models.IntegerField()),
                ('ESI_Number', models.IntegerField()),
                ('Mobile_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Aadhar_No', models.IntegerField()),
                ('PAN', models.CharField(max_length=25)),
                ('Bank_Acc_NO', models.IntegerField()),
                ('IFSC_Code', models.CharField(max_length=25)),
                ('Bank_Name', models.CharField(max_length=25)),
                ('Emergency_Contact_No', models.IntegerField()),
                ('Contact_No', models.IntegerField()),
                ('Sur_name', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('Experience', models.CharField(max_length=25)),
                ('Remarks', models.TextField()),
                ('Salary', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
