# Generated by Django 4.2.9 on 2024-06-03 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Overtime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
