# Generated by Django 4.2.9 on 2024-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_dol_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='Overtime',
            field=models.TimeField(),
        ),
    ]
