# Generated by Django 4.2.9 on 2024-06-07 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_overtime_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='Overtime',
        ),
        migrations.AddField(
            model_name='overtime',
            name='Overtime_hours',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='overtime',
            name='Overtime_minutes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterModelTable(
            name='overtime',
            table=None,
        ),
    ]
