# Generated by Django 4.2.9 on 2024-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_aadhar_no_alter_employee_bank_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_Name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
