# Generated by Django 4.2.9 on 2024-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_overtime_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Esic_no',
            field=models.IntegerField(default=0),
        ),
    ]
