# Generated by Django 4.2.9 on 2024-07-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_employee_esic_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_code',
            field=models.IntegerField(default=0),
        ),
    ]
