# Generated by Django 4.2.9 on 2024-07-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_emp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Emp_code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
