# Generated by Django 5.0.1 on 2024-07-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
